[project]
name = "offlineonline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyautogui>=0.9.54",
    "selenium>=4.39.0",
    "torch>=2.9.1",
    "undetected-chromedriver>=3.5.5",
    "xvfbwrapper>=0.2.18",
]
